# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# Based on: https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare virtual display for Tk
        run: |
          sudo apt install xvfb              # virtual display for tk tests

      - name: Run tests
        run: |
          Xvfb :1 -screen 0 1600x1200x16  &  # create virtual display with size 1600x1200 and 16 bit color. Color can be changed to 24 or 8
          export DISPLAY=':1'              # tell X clients to use our virtual DISPLAY :1.0
          pytest
